// Generated by Selenium IDE
package seleniumexample2;
import org.junit.Test; 
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.firefox.FirefoxDriver;

import dev.failsafe.Timeout;

import org.openqa.selenium.JavascriptExecutor;

import java.util.*;
import java.util.concurrent.ForkJoinPool.ManagedBlocker;
import java.util.concurrent.TimeUnit;

public class UntitledTest {
  private WebDriver driver;
  //private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
 //   vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void untitled() throws Exception {
	 
    driver.get("https://www.google.com/");
    driver.findElement(By.name("q")).sendKeys("car");
    driver.findElement(By.cssSelector(".QCzoEc > svg")).click();
    driver.findElement(By.cssSelector(".QCzoEc > svg")).click();
    driver.findElement(By.cssSelector(".QCzoEc > svg")).click();
  }
}
